use user_database;
select * from plant_info;
drop table plant_info;
drop table login;
select * from users;

create database plants;
use plants;

CREATE TABLE plant_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    plant_name VARCHAR(255),
    botanical_name TEXT,
    family VARCHAR(255),
    vernacular_names TEXT,
    introduction TEXT,
    botanical_description TEXT,
    distribution TEXT,
    major_chemical_constituents TEXT,
    properties TEXT,
    part_used VARCHAR(255),
    dosage TEXT,
    uses TEXT,
    food_recipes TEXT,
    precautions TEXT,
    mode_of_propagation TEXT,
    ayurvedic_formulations TEXT
);

INSERT INTO plant_info (
    plant_name, 
    botanical_name, 
    family, 
    vernacular_names, 
    introduction, 
    botanical_description, 
    distribution, 
    major_chemical_constituents, 
    properties, 
    part_used, 
    dosage, 
    uses, 
    food_recipes, 
    precautions, 
    mode_of_propagation, 
    ayurvedic_formulations
) VALUES (
    'Adulsa', 
    'Adhatoda vasica Nees. (A. zeylanica Medicus)', 
    'ACANTHACEAE', 
    'Hindi:Adusa Telugu:Addasaramu English: Malabar Nut Bengali: Bakas Punjabi: Vamsa Marathi: Adulsa Gujarati: Araduso Tamil: Eidhadad', 
    'Adulsa is highly valued in Ayurveda and traditional medicine for its effectiveness in treating respiratory ailments. It is known for its expectorant, bronchodilator, and anti-inflammatory properties and has been mentioned extensively in Ayurvedic texts.', 
    'A dense shrub. Leaves: elliptic or elliptic-lanceolate, acuminate. Flowers: in dense spikes, white; bracts ovate or obovate; calyx deeply five-lobed; stamens glabrous. Fruits: four-seeded capsules. Seeds: glabrous. Flowering and fruiting between February-May.', 
    'Tropical and subtropical regions of India and grows abundantly in plains, foothills, and moist regions.', 
    'Vasicine (peganine), vasicinine, β-sitosterol, Kaempferol, 3-sophoroside, luteolin, tritriacontane, adhatodic acid, Carotene, vasakin, vasicinol, 1-α-hydroxyvasicine, vasicinone, vit-C, vasicol, vasicinol, vasicinolone, adhatodine, adhavasinone, anisotine, vasicolone, vasicolinone, etc.', 
    'Rasa: Tikta, Kaṣaya Guna: Laghu, Rūkṣa Vīrya: Śīta Vipāka: Kaṭu Karma: Kapha-pittahara, Hṛdya, Svarya', 
    'Leaf, root, flower', 
    'Leaf juice: 10-20 ml Root decoction: 40-80 ml Flower juice: 10-20 ml', 
    '1. Cough: Decoction of 5-10 Vasa leaves is beneficial in cough. 2. Hemorrhagic disorders: Juice of Vasa leaves (5-15 ml) with honey is useful in hemorrhagic epistaxis and hemoptysis. 3. Scanty menstruation: Decoction or juice of Vasa leaves is beneficial.', 
    '1. Adulsa Kadha: An Ayurvedic remedy for cough and cold. This concoction typically involves boiling Adulsa leaves with other herbs like Tulsi, Ginger, Black pepper, Ajwain, and Turmeric. 2. Adulsa Decoction: Boil crushed leaves with water, add honey, and consume to treat respiratory issues. 3. Adulsa Herbal Tea: Brew leaves with ginger and black pepper for a soothing tea to relieve cough and cold. 4. Adulsa Syrup: Prepare a syrup by boiling leaves, straining, and adding jaggery for daily use in managing asthma and cough.', 
    'Intake in excessive quantity may result in diarrhea, vomiting, and excessive menstrual bleeding.', 
    '1. Stem cuttings of 15-20 cm long with 3-4 nodes are ideal for planting done in March-April. 2. Tender stem cuttings are planted in poly bags/pots filled with farm yard manure, top soil, and sand in the ratio 1:1:1. 3. Cuttings will root readily and will be ready to transplant to main field after two months.', 
    'Vasavleha, Vasarishta.'
),
(
    'Alovera', 
    'Aloe Vera chinensis', 
    'LILIACEAE', 
    'Hindi:Gheekuvar English: Indian aloe Telugu: Kalabanda, Lolisāra Kannada: Kumari Malayalam: Kumari Tamil- Chiruli', 
    'Aloe Vera has been used for centuries in traditional medicine and Ayurveda for its healing and rejuvenating properties. It is highly valued for its benefits to the skin, digestion, and immune system, and it is an essential component of many herbal formulations and cosmetics.', 
    'Aloe Vera is a succulent plant that grows up to 60-100 cm in height. It has thick, fleshy, green to grey-green leaves with serrated edges. The plant produces yellow tubular flowers and thrives in arid climates.', 
    'Widely cultivated in India and other tropical and subtropical regions of the world. It is commonly found in household gardens and commercial farms.', 
    'Aloe-Emodin, aloctin A (glycoprotein), aloenin (bitter glucoside), barbaloin, chrysophanol-sitosterol, glycoside, galactose, mannose; aldopentose, aloesin, aloesone, alocutin A & B etc.', 
    'Rasa:Tikta Vīrya: Śīta Karma:Kapha-vātahara, Cakşuşya, Vrşya, Brmhana, Rasayana, Bhedana Vipāka: Katu Guna: Guru,Snigdha,Picchila', 
    'Leaves', 
    'Fresh juice 10-20 ml; Aqueous Extract 100-300 mg', 
    '1. Burns and Wounds: Due to its soothing, moisturizing, and cooling properties, Aloe vera gel is used externally to treat burns. Gel, mixed with turmeric powder and coconut oil aids early healing of wounds and ulcers including anal fissure and skin problems. 2. Digestive Problems: 2 to 3 spoons of Aloe gel mixed with a glass of water should be taken in all types of digestive and liver problems. 3. Adjuvant Therapy: Aloe vera gel may be taken with antibiotics, NSAIDs (Non-steroidal Anti-Inflammatory Drugs) and chemotherapy to eliminate drug-induced gastritis and other adverse effects. 4. Multiple Uses: Useful in various diseases such as diabetes, Arthritis, eye disease, spleen and liver complaints, etc.', 
    '1. Alovera juice: A simple and refreshing option is aloe vera juice, made by blending the gel with water, lemon juice, and honey. 2. Aloe Vera Smoothie: Mix Aloe Vera gel with fruits like banana and mango for a nutritious smoothie. 3. Aloe Vera Salad: Add Aloe Vera gel to a vegetable salad for a unique and healthy dish.', 
    'Contraindicated in cases of known allergy to the plant. It may cause redness, burning, stinging sensation and rarely generalized dermatitis in sensitive individuals. Oral intake of Aloe vera is not be recommended during pregnancy as it may cause stimulation of uterine contractions. It may sometimes cause gastrointestinal distress in the infant if given to breastfeeding mothers.', 
    '1. Methods of propagation are sexual (with seeds), vegetative (by pups obtained from the plants themselves or by the micro-propagation method). 2. It is grown successfully in marginal to sub-marginal soils having low fertility. It is observed that its growth was faster under medium fertile heavier soil such as black cotton soils of central India. 3. It is cultivated in pots outdoor or indoor, kept on sunny window.', 
    'Kumari Asava, Rajahaparvartani Vati, Aloe Vera Juice, Pulp, Cream'
),
(
    'Amla', 
    'Emblica officinalis Gaertn (Phyllanthus emblica Linn.)', 
    'EUPHORBIACEAE', 
    'Hindi: Amla English: Indian gooseberry Telugu: Usiri kaya Tamil: Nellikkai Malayalam: Nelli Kannada: Nelli', 
    'Amla, also known as the Indian Gooseberry, is revered in Ayurveda as a powerhouse of nutrients and therapeutic benefits. It is a rich source of Vitamin C and antioxidants, making it a key ingredient in many herbal formulations for immunity, digestion, and skin health.', 
    'It is a large deciduous tree with greenish-grey or red bark, peeling off in scales. Leaves: pinnate, distichously close-set, linear-oblong, obtuse. Flowers: densely fascicled along the branchlets, yellow; males on slender pedicles, females sub-sessile. Fruits: berry, depressed globose, succulent, yellow or pink when ripe, obscurely 6-lobed. Seeds: trigonous. (flowers in Feb.-May and fruits in Oct.-April).', 
    'Wild/cultivated throughout tropical India.', 
    'Root: Ellagic acid, lupeol, oleanolic aldehyde Bark: Leucodelphinidin, procyanidin, tannin etc. Fruit: Vit. C, phyllemblin, linolic acid, indole acetic acid, emblicanin A & B, trigalloylglucose, terchebin, corilagin, ellagic acid, phyllemblic acid & salts, emblicanin A & B.', 
    'Rasa: Amla pradhana, Pañca rasa (except Lavana) Vīrya: Śīta Karma: Tridosahara, Vayahsthapana, Rasāyana, Cakşuşya, Vrsya, Somaroga, Pradara, Mūtrakṛcchra, Śūla. Vipāka: Madhura', 
    'Fruit pulp/Fruit rind', 
    'Fresh juice 10-20 ml; Powder 3-6 g.', 
    '1. Enhancing Immunity: The fruit is useful in the form of juice, powder, food recipe or as part of a formulation in enhancing immunity against diseases. 2. Urinary Problems: 10 to 20 ml of fresh juice of Amla with jaggery is beneficial in burning micturition. 3. Reproductive Problems: Fresh juice of Amla or powder is useful in menorrhagia and leucorrhea. 4. Diabetes/Prediabetes: Powder of Amla and turmeric (2-4gm each in equal quantity) with water will be an effective remedy. 5. Anemia: Juice of Amla is beneficial. 6. Acid Peptic Disorder: Amla powder (2gm-3gm) with warm water will help in hyperacidity. 7. Constipation: 5 to 10 gm of Amalaki powder taken with warm water during bedtime is useful in relieving constipation. 8. Cosmetics: Amla boiled with any oil is used traditionally for the treatment of dandruff and hair loss.', 
    '1. Amla Murabba: Boiled Amla pieces are soaked in sugar or jaggery syrup and flavored with cardamom. This easy recipe is suitable for everyday use to boost immunity and to manage health issues mentioned above. This preparation is not recommended for diabetics due to the presence of sugar/jaggery. 2. Amla Chutney: Amla along with fennel seeds, chillies, salt, and other spices as per the choice are grounded in coconut. 3. Amla Pickle: Boil the Amla with salt and water till it becomes tender, drain the water. Heat some oil and add mustard seeds, asafoetida, and chilli powder. Mix well and add Amla. Stir till mixed well and excess water gets fully evaporated.', 
    'Intake in excessive quantity may result in loose motion.', 
    '1. It is propagated by seeds as well as by stem cuttings. 2. When the stem divisions are used as the planting material, the selected division should have 3-4 nodes. 100% sprouting will be seen in 7-10 days. Planting may be done in the month of June. 3. Collect the fresh seeds during February-March. Sow them on nursery beds or directly in the fields. 60% of germination would be obtained within 10 days.', 
    'Chyawanprash, Triphala Churna, Amalaki Churna.'
),
(
    'Banana', 
    'Musa paradisiaca Linn. (M. sapientum Linn.)', 
    'MUSACEAE', 
    'Hindi: Kela English: Banana tree Tamil: Vālakkai Telugu: Aratichettu', 
    'Banana is a staple fruit in many regions and is revered in Ayurveda for its nutritional and medicinal properties. It is a rich source of energy, vitamins, and minerals. The plant is also valued for its medicinal uses, with its fruit, stem, leaves, and flowers all being utilized in traditional medicine.', 
    'Habit: Herbaceous perennial Stem: False stem formed by overlapping leaf sheaths Leaves: Large, oblong leaves with prominent midrib Flowers: Inflorescence emerges from the base of the plant, producing male and female flowers Fruit: A fleshy berry containing seeds (in wild varieties) or seedless in cultivated varieties', 
    'Widely cultivated in tropical and subtropical regions around the world. It thrives in humid climates with well-drained, fertile soils.', 
    '5-hydroxytryptamine etc., in raw pulp or banana; rhizome ash is used; Fruit- Ca, P, Oxalic acid, Vitamins etc.', 
    'Rasa: Madhura Vīrya: Śīta Guna: Guru, Snigdha Vipāka: Madhura Karma: Pitta-vāta hara, Brmhana, Vrsya', 
    'Tuber, flower, fruit, pith of stem', 
    'Fresh juice 10-20 ml, powder 1-3 g.', 
    '1. Peripheral Neuropathy: The crushed flowers of kadali (banana) tree fried with castor oil slightly and be used for fomentation or as a bandage on the extremities for burning sensation. 2. Constipation: Ripened banana as a fruit is a good Laxative, Nutritive and Diuretic. 3. Indigestion: It is good to eat food in Plantain leaf as it helps to treat Indigestion and body heat. 4. Traumatic swellings: The roots of Plantain tree is crushed well and the paste used for bandaging over traumatic swellings. 5. Urinary Calculi: Regular intake of 20ml of Plantain stem juice twice daily for 3 months is beneficial to eliminate Urinary calculi. 6. Fungal infection (Sidhma): Paste of 2 gms of Banana leaf alkali (Burned leave ash) mixed with 2 gms of turmeric powder applied over the affected skin is beneficial in Fungal infection.', 
    '1. Banana Smoothie: Blend ripe banana with milk and honey for a nutritious drink. 2. Banana Flower Curry: Cook banana flowers with spices and coconut for a traditional dish. 3. Banana Stem Juice: Extract juice from the stem and consume it with a pinch of salt for detoxification.', 
    'Excessive consumption of bananas may lead to bloating or gas in some individuals. People with kidney issues should monitor potassium intake and consult a physician. Avoid consuming unripe bananas if suffering from severe constipation.', 
    '1. Banana is propagated through suckers or tissue culture. It requires fertile, well-drained soil and adequate water for optimal growth.', 
    'Kadali Churna, Kadali Ksheera, Banana Stem Juice'
),
(
    'BeetelLeaf(Pan)', 
    'Piper betle Linn.', 
    'PIPERACEAE', 
    'English : Betel, betel pepper Hindi : Pan, tambuli Kannada : Villayadele Malayalam : Vettilakkoti, kotinnali Sanskrit : Tambulavalli, tambulah Tamil : Vetrilai Nagavalli, Kammaaruvetritai. Telugu : Tamalapaku, nagavalli Unani : Paan, Tambool.', 
    'Betel leaf holds a significant place in traditional medicine and cultural practices across Asia. Known for its medicinal and stimulant properties, it is often used in Ayurveda for digestion, oral health, and wound healing. Betel leaf is also an integral part of rituals and cuisine.', 
    'Perennial climber Leaves: simple, alternate, broadly ovate Male spike: dense – cylindrical Female spike: pendulous. Fruits: are rarely produced', 
    'Widely in India, Southeast Asia, and tropical regions. It thrives in warm, humid climates with fertile, well-drained soils.', 
    'beta- and gamma- sitosterol, hentriacontane, pentatriacontane, n-triacontanol, stearic acid and chavicol, carvacrol, eugenol, chavicol, allyl catechol, cineole, estragol, caryophyllene, cardinene, pcymene, eugenol methyl ether', 
    'RASA: tikta, katu, kashaya GUNA: laghu, ruksha, tikshna, vishada, kshara VIRYA: ushna VIPAKA: katu Karma: balyam, ruchyam, deepana, pachana, rochanam, raktha pitta vardanam stimulant, carminative, astringent, antiseptic', 
    'Whole Plant', 
    'Leaf juice 5-6 ml Powder 2-4 g Decoction 50-100 ml', 
    '1. Colic: Apply castor oil on smooth surface of 2-3 broad betel leaves. Warm them little and place them on stomach. By doing this 3-4 times the colic pain will subside. 2. Bad breath: Chewing betel leaves after meals helps to reduce foul breath as well as eases digestion. It will increase secretion of digestive juices, decreases bloating of stomach, cleanses the oral cavity, reduces constipation. 3. Wound: Grind the leaves, extract the juice, apply on the wounds, wrap a betel leaf as well as bandage the wound. 4. Burns: Mix betel leaves paste with honey and apply over the burns. 5. Sore throat: Take 5 ml of betel leaves juice and 5gms of licorice powder mix in a glass of warm water. This water can take internally as well as gargle. Singers can frequently utilize this cure to maintain their vocal chords healthy. 6. Cough: Betel leaves drenched in mustard oil, slightly warmed and applied on the chest, reduces cough as well as breathing problems in children.', 
    '1. Betel Leaf Tea: Brew fresh betel leaves in water, add honey, and consume for respiratory relief. 2. Betel Leaf Chutney: Blend betel leaves with tamarind, spices, and jaggery for a flavorful chutney. 3. Stuffed Betel Leaves: Stuff betel leaves with coconut, jaggery, and cardamom for a sweet dish.', 
    'Excessive chewing of betel leaves, especially with tobacco or lime, can harm oral health. Pregnant women should consult a physician before consuming betel leaves. Avoid in cases of gastritis or hyperacidity due to its warming nature.', 
    '1. Betel leaf is propagated through stem cuttings. 2. It requires fertile, well-drained soil and thrives in warm, shaded areas with adequate moisture.', 
    'Tambula Patra Swarasa, Tambula Taila, Betel Decoction'
),
(
    'Brahmi', 
    'Centella asiatica (Linn.) Urban (Hydrocotyle asiatica Linn.)', 
    'UMBELLIFERAE', 
    'Hindi: Brahmi, Bagsag Bengali: Thul-kudi Telugu: Sarasvathy Aku Tamil: Vallari Kirai Marathi: Karivan Gujarati: Khanda Brahmi', 
    'Brahmi, also known as Mandukaparni in Ayurveda, is highly esteemed for its cognitive-enhancing and rejuvenating properties. It is an adaptogen, which helps the body to cope with stress, and is primarily used for improving memory, concentration, and mental clarity. It is also beneficial for skin health and overall vitality.', 
    'It is a prostrate herb; rooting at the nodes. Leaves: usually glabrous, orbicular-reniform, or lobulate. Bracts small, ovate. Flowers: white, borne in 3-6 flowered umbels. Fruits & Seeds: laterally compressed. (Flowers and fruits from April to June).', 
    'Native to India in waste places, gardens, and that localities. Found in tropical America, Africa, West Pakistan, China, Japan, and the Pacific.', 
    'Asiatic acid, centelic acid, centellic acid, centoic acid, pctic acid, carotene, centellose, hydrocotylin, asiaticosides A & B, caryophylleae, g-sitosterol, vallerine, etc.', 
    'Rasa: Tikta Guna: Raghu Virya: Sita Vipaka: Madhura Karma: Kapha-pitta hara, Medhya, Vayahsthapana', 
    'Whole Plant', 
    'Juice 10-20 ml; Powder 3-6 g.', 
    '1. Brahmi is considered a brain tonic used for improving memory and overcoming mental stress, fatigue. 5 to 10 ml fresh juice or powder is given with milk in sleeplessness, anxiety, cognitive problems, headache, or neurological problems. 2. It is useful in neurological problems such as convulsions along with standard therapy.', 
    '1. Brahmi chutney when ground with coconut, green chilly, tamarind, and coconut. 2. Juice of leaves or whole plant can be used in lemon sharbat or herbal tea.', 
    'Excessive use every day may lead to giddiness or headache.', 
    '1. Stolon cuttings with a minimum of one node are planted horizontally at a distance of 30 cm x 30 cm. 2. Watering should be done just after transplantation and subsequently at an interval of 2 to 3 days. 3. To begin with, weeding is done at an interval of 15-20 days. Thereafter, it is done as and when required. Similarly, it can be grown in pots.', 
    'Saraswataristha, Brahma Rasayana'
),
(
    'CurryLeaves', 
    'Murraya koenigii (L.) Spreng.', 
    'RUTACEAE', 
    'Hindi: Meetha Neem Telugu: Karivepaku Bengali: Barsunga Gujarati: Mitho Limdo', 
    'Curry leaf is an integral part of Indian cuisine and is also well-known in Ayurveda for its medicinal properties. It has been used traditionally to manage gastrointestinal disorders, improve hair health, and regulate blood sugar levels.', 
    'Curry leaf is a small to medium-sized aromatic shrub or tree that grows up to 4-6 meters in height. The leaves are pinnate, shiny, and dark green with a characteristic aroma. The plant bears small white flowers and produces small black berries.', 
    'Widely cultivated in India and neighboring countries. It is also found in tropical and subtropical regions globally.', 
    'Alkaloids (mahanimbine, girinimbine), Essential oils (linalool, caryophyllene), Flavonoids, Phenolic compounds', 
    'Rasa: Tikta, Katu Vīrya: Uṣṇa Guna: Laghu, Rūkṣa Vipāka: Katu Karma: Deepana (appetizer), Pachana (digestive), Kapha-Vatahara', 
    'Leaves, Roots, Bark', 
    'Fresh juice: 10-20 ml; Powder: 2-3 grams daily', 
    '1. Digestive Disorders: Curry leaves improve digestion and are effective in managing flatulence and diarrhea. 2. Diabetes Management: Regular consumption helps regulate blood sugar levels. 3. Anemia: Rich in iron and folic acid, curry leaves help combat anemia. 4. Liver Health: Acts as a hepatoprotective agent and supports detoxification of the liver. 5. Skin and Hair Health: Curry leaf oil and paste nourish the scalp, prevent premature greying, and treat dandruff. 6. Antioxidant and Antimicrobial: Protects cells from oxidative damage and helps fight infections. 7. Weight Management: Improves metabolism and aids in weight management.', 
    '1. Curry Leaf Chutney: Leaves blended with coconut, green chilies, and tamarind, served as a side dish. 2. Curry Leaf Rice: Fried curry leaves mixed with rice, spices, and nuts for a flavorful dish. 3. Curry Leaf Soup: A light soup made with curry leaves, black pepper, and ginger.', 
    'Excessive consumption may lead to mild gastrointestinal discomfort. Pregnant and lactating women should consult a healthcare provider before use. Not suitable for individuals with a known allergy to Rutaceae family plants.', 
    '1. Curry leaf plant propagates through seeds and cuttings. 2. It grows well in well-drained soil and sunny locations.', 
    'Curry Leaf Churna, Curry Leaf Taila, Curry Leaf Kadha'
),
(
    'Drumstick', 
    'Moringa pterygosperma Gaertn. (M. oleifera Lam.)', 
    'MORINGACEAE', 
    'Hindi: Sahijana, English: Horse-radish tree, Drumstick plant, Telugu: Munaga chettu, Munakkai chettu, Tamil: Murungai', 
    'Moringa, commonly known as Drumstick, is highly regarded in both traditional medicine and modern herbalism for its wide range of nutritional and therapeutic properties. Nearly every part of the tree, including the leaves, pods, flowers, and seeds, is used for its medicinal and nutritional benefits.', 
    'A small or medium-sized tree, growing up to 10m. Bark: corky, soft, back, deeply fissured. Wood is soft. Leaves: tripinnate, 30.5-61.0 cm long, leaflets elliptic. Flowers: bisexual, irregular, fragrant, white, in large panicles. Fruits: pod, triangular ribbed, pendulous, greenish, 22.5-50.0 cm or more in length. Seeds: trigonous, winged (flowers in February-March and fruits in March-April).', 
    'Native to the Indian subcontinent, Moringa is now cultivated in many tropical and subtropical regions of the world. It thrives in dry, arid regions but is also grown in tropical and subtropical climates.', 
    'Bark: Sterols, terpenes (bayrenol). Leaves: Amino acids (aspartic and glutamic acid, serine, glycine etc.). Whole Plant: Moringine, moringinine, bayrenol, indole acetic acid, pteregospermine, carotene etc. Flowers: Quercetin, kaempferol.', 
    'Rasa: Katu, Tikta. Guna: Laghu, Rūkṣa, Tīkṣna. Vīrya: Uṣṇa. Vipāka: Katu. Karma: Kapha-vātahara, Śukrala, Grāhi, Dīpana, Hrdya, Krmighna, Cakṣusya.', 
    'Root bark, stem bark, leaves, fruits, seeds', 
    'Root bark juice: 10-20 ml; Seed powder: 1-3 g; Stem bark decoction: 50-100 ml', 
    '1. Anemia: 10-20 ml juice or use of leaves or pods Moringa in the form of vegetable. 2. Asthma: Consumption of about 100 ml of decoction of a fistful of drumstick leaves is beneficial in bronchitis and asthma. 3. Swellings & wound: Application of warm paste made up of bark and leaves of Moringa is useful in relieving pain and swelling in joints and abscesses. Its paste is also helpful in wound healing. 4. Heart disease: This has cholesterol-lowering action and stabilizes blood pressure. Therefore, use of leaves, flowers, and pods in any form is good for the heart. 5. Other Uses: Moringa is helpful in various eye problems, improving vision, amenorrhea, dysmenorrhea, and as a tonic to improve immunity.', 
    '1. Drumstick pods & leaves are popularly added in sambar, daal, and vegetables. 2. It can be used in paratha as any other leafy vegetable. Chopped leaves can be added in the dosa along with tomato and onion. 3. Tender drumstick pods or leaves may be sautéed and seasoned with chopped onion, garlic, chili, and salt. 4. The leaves can be used in zunka, a recipe popular in Maharashtra and its neighboring parts of Karnataka.', 
    'There are no contraindications for the use of any part of Moringa, however, excessive intake may lead to an increase in body heat and Pitta in some people. Intake may be avoided during heavy menstrual bleeding.', 
    '1. It grows best in direct sunlight. Moringa can be propagated from seed or cuttings. Direct seeding is possible because the germination rate is high. Soak the seeds in water overnight and crack the shells before planting. Remove shells and plant kernels only. Moringa seeds can be germinated year-round in well-draining soil. 2. For vegetative propagation, use hardwood and not greenwood. Cuttings should be 45 cm to 1.5 m long and 10 cm thick. Cuttings can be planted directly or in sacks. Plant one-third of the length in the ground and do not overwater. If the soil is too heavy or wet, the roots may rot.', 
    'Shigru Guggulu'
),
(
    'Eranda', 
    'Ricinus Communis Linn.', 
    'EUPHORBIACEAE', 
    'Hindi: Erand, English: Castor, Bengali: Rehri, Bherenda, Telugu: Āmudamu, Tamil: Amanakku, Marathi: Erandi, Malayalam: Avanakku, Gujarati: Diveligo', 
    'Eranda, also known as Castor, is renowned for its medicinal properties, particularly its oil. Castor oil is commonly used as a laxative, in treating skin conditions, and for its anti-inflammatory and antimicrobial effects. The plant also has several traditional uses in Ayurveda for treating a variety of health issues.', 
    'An evergreen, glabrous shrub, 2-4.5 m high. Leaves: palmately 7-many-lobed, lobes oblong to linear, acute or acuminate. Flowers: in large terminal subpanicled racemes; in a dense globose head of branched filaments and anthers; yellowish. Fruits: Capsules, globosely oblong, smooth or echinate. Seeds: oblong, smooth, mottled.', 
    'Native to Eastern Africa and India, the castor plant is widely cultivated in tropical and subtropical regions around the world. It thrives in dry, sandy, and well-drained soils.', 
    'Seeds & Leaves: ricinine (toxic alkaloid), 1-methyl-3-cyano-4methoxy-2-pyridone. Seed Coat: Lupeol, lipids, phosphatides etc. Seed Oil: Arachidic, ricinoluc, palmitic, stearic etc., acids; hexadecanoic, hydrocyanic & uric acids; squalene and tocopherols etc.', 
    'Guṇa: Snigdha, Tīkṣṇa, Sūkṣma. Rasa: Madhura, Katu, Kaṣāya. Vīrya: Uṣṇa. Vipāka: Madhura. Karma: Kapha-vātahara, Recana, Vrsya (root).', 
    'Root, leaf, seed, oil', 
    'Root powder: 3-5 g, decoction: 50-100 ml; Seed: 1-5 numbers; Oil: 5-10 ml', 
    '1. Jaundice: Fine paste of 5gms Tender leaves of Eranda is administered orally early in the morning on an empty stomach, helps to cure jaundice. 2. Joint Pains: Mature leaves paste mixed with little crystal salt and warmed. This lukewarm paste is applied over the muscular swelling and joint pains. 3. Scrotal Enlargement: 10ml of castor oil mixed with one cup of milk should be taken daily once during night time after food for a month. 4. Sciatica: 10 grams of Eranda root powder boiled in 100ml of milk and reduced to half is administered orally twice daily to relieve the pain in sciatica. 5. Colic: Whole leaf of castor smeared with sesame oil and warmed slightly. This is applied over the abdomen (Umbilicus) to pacify abdominal colic. 6. Worm Infestation: 2 gms of Palasha seeds powder is taken along with 10 ml of castor oil at bedtime. Pinworms are relieved within 3-4 days by this medication. 7. Lactation: The leaves are heated and applied over the breast as a bandage to induce milk secretion in lactating mothers. It is also beneficial in breast abscesses.', 
    'Castor oil is not typically used in food preparation due to the toxicity of ricin in raw seeds. However, it is consumed medicinally for its laxative properties.', 
    'Toxicity: Castor seeds are highly toxic if consumed raw due to the presence of ricin. Always use only purified castor oil. Pregnancy: Castor oil should be avoided during pregnancy unless prescribed by a doctor, as it may stimulate uterine contractions. Overuse: Overuse of castor oil as a laxative can lead to dehydration and electrolyte imbalances. Children: Avoid using castor oil for children under the age of 12 unless directed by a healthcare provider.', 
    '1. Castor plants are propagated by seeds. The seeds are sown in well-drained soil, and the plant thrives in warm climates with plenty of sunlight.', 
    'Eranda Taila, Castor Oil Enema'
),
(
    'Gokarna', 
    'Clitoria ternatea Linn.', 
    'FABACEAE', 
    'Hindi: Koyala, Telugu: Dintena', 
    'Gokarna is highly valued in Ayurveda for its medicinal properties. It is known for its ability to treat various health conditions, including skin disorders, digestive issues, and respiratory problems. Its roots and leaves are particularly used for their therapeutic effects, and the plant is considered an important herb in traditional healing systems.', 
    'It is a perennial climber. Leaves: pinnately 3-7 foliolate. Flowers: showy, blue or white, petals unequal, style bearded below the stigma. Fruits: pods, linear, compressed. Seeds: 6-10, black (Flowers in rainy season and fruits in winter).', 
    'Gokarna is found in tropical and subtropical regions of India, Africa, and some parts of Southeast Asia. It grows in sandy soils and is commonly found in coastal areas.', 
    'Aparajitin, taraxerol, taraxerone, sitosterols, robinin, quercetin, kaempferol; ternatins A,B,C,D etc.', 
    'Rasa: Katu, Tikta, Kaşāya. Guṇa: Laghu, Rūkşa. Vīrya: Šīta. Vipāka: Katu. Karma: Tridoşahara, Medhya, Visaghna, Cakşuşya.', 
    'Root/root bark, seeds', 
    'Root powder: 1-3g; Seed powder: 1-2 g.', 
    '1. Leucoderma: The leaves paste of Aparajita applied thickly on the vitiligo patches and exposed to sunlight. It has to continue for a minimum of 1 month to stimulate melanocytes. 2. Filarial swelling: 5gms of Aparajita root paste should be given internally twice daily in filariasis to relieve the swelling. 3. Memory Enhancer: The fresh root paste of Aparajita should be given in a dose of 1-3 grams with ghee twice daily for increasing memory and intelligence. 4. Menorrhagia: 1 gram of Aparajita flowers powder should be given thrice daily with honey for bleeding disorders of the uterus. 5. Conjunctivitis: The flowers of Aparajita are pounded with cow milk and applied over the closed eyes. It alleviates conjunctivitis. 6. Toothache: Aparajita root with black pepper should be kept in the mouth to pacify the toothache. 7. Wound: Fine leaves paste of Aparajita should be applied over the wound as it has antifungal and antibacterial properties, greatly reducing the infection and healing the wound very fast.', 
    '1. Gokarna Herbal Tea: Boil Gokarna leaves with other herbs like ginger and black pepper to make a rejuvenating tea for respiratory and digestive health. 2. Gokarna Decoction: Prepare a decoction by boiling the roots in water, which can be consumed to promote kidney health and treat urinary problems.', 
    'Gokarna should be used with caution in pregnant women as its effects during pregnancy are not fully studied. Those with kidney or liver conditions should consult a doctor before using Gokarna. Overuse may cause gastrointestinal upset, including diarrhea or stomach cramps.', 
    '1. Gokarna is propagated primarily through seeds. 2. It thrives in sandy, well-drained soil and requires a warm, tropical climate for optimal growth.', 
    'Gokarna Churna, Gokarna Kvath (Decoction), Gokarna Taila'
),
(
    'Hibiscus', 
    'Hibiscus rosa-sinensis Linn.', 
    'MALVACEAE', 
    'English: Shoe flower, Telugu: Mandara-puvvu', 
    'Hibiscus is well known for its vibrant flowers and is a common ingredient in herbal medicine. Its flowers, leaves, and roots are used in traditional systems of medicine such as Ayurveda for their numerous therapeutic properties. Hibiscus tea, made from the flowers, is popular worldwide for its refreshing taste and health benefits.', 
    'An evergreen woody glabrous showy shrub, 1.5-2.4 m high. Leaves: coarsely toothed above, entire below, ovate, bright-green. Flowers: axillary, solitary, campanulate, red, blue, yellow or white, 10.2-15.2 cm diameter. Capsules: (rare) rotund, many-seeded.', 
    'Hibiscus is native to East Asia but is now cultivated in tropical and subtropical regions around the world, including India, Africa, and parts of the Caribbean. It thrives in full sun and well-drained, moist soil.', 
    'Taraxeryl acetate, β-sitosterol, cyanin, cyanidin glucosides, thiamine, riboflavin, niacin, ascorbic acid, carotene etc.', 
    'Rasa: Katu, Tikta, Madhura. Vīrya: Ushṇa. Guṇa: Laghu, Rūkṣa. Vipāka: Katu. Karma: Vata-Kapha hara, Deepana (digestive stimulant), Rasayana (rejuvenative), Raktashodhaka (blood purifier), Antioxidant.', 
    'Flowers, leaves, root', 
    'Hibiscus Tea: 1-2 cups daily. Hibiscus Powder: 1-2 grams per day. Hibiscus Oil (Topical): As needed for hair and skin care.', 
    '1. Leucorrhoea: 3-5 flowers of Japa paste boiled in 100ml of milk till it reduces to 50ml, added with little jaggery and 3 grams of yavani (Trachyspermum ammi), should be given in leucorrhoea daily once. 2. Insomnia: The petals of the flowers of Japa, one part, and six parts of water are mixed, heated on a little flame, and reduced to 1/4th part. Then jaggery is added to it and prepared into syrup. This is given in the dose of 10 ml for urinary diseases, insomnia, and psychiatric ailments. 3. Hair fall: The juice of Japa petals boiled in coconut oil till the water content disappears. Application of this oil on the head gives coolness to the entire body and is very effective for hair fall. 4. Dandruff: The leaves are crushed well and squeezed to extract the mucilaginous content. This should be applied to the head before 2 hours of a head bath. It relieves dandruff and promotes hair growth. 5. Boils: The leaves and young flower buds paste of Japa is used as a poultice on boils. 6. Cough: Drinking twice daily Hibiscus tea (1-2 flowers boiled in 50ml of water for 5 to 10 minutes) is rich in antioxidants, can protect the liver, relieves cough, and reduces fever.', 
    '1. Hibiscus Tea: Steep dried hibiscus flowers in hot water for 5-10 minutes. Sweeten with honey or sugar if desired. 2. Hibiscus Syrup: Boil hibiscus flowers with sugar and water to make a flavorful syrup, which can be added to drinks or desserts. 3. Hibiscus Salad: Add fresh hibiscus petals to salads for a decorative and flavorful touch.', 
    'Pregnancy: Hibiscus may have uterine-stimulating effects, so it should be avoided during pregnancy unless prescribed by a doctor. Low Blood Pressure: Since hibiscus may lower blood pressure, those with hypotension should avoid excessive consumption. Allergies: Individuals with allergies to hibiscus or related plants should avoid it.', 
    '1. Hibiscus can be propagated by seeds, cuttings, or layering. 2. It thrives in well-drained, loamy soil and requires full sunlight to grow. It is tolerant of heat but needs regular watering.', 
    'Hibiscus Churna, Hibiscus Oil, Hibiscus Kvath (Decoction)'
),
(
    'Jamun', 
    'Syzygium cumini (Linn.) Skeels (Eugenia jambolana Lam., Myrtus cumini Linn.)', 
    'MYRTACEAE', 
    'Hindi: Jamun, English: Jaman, Bengali: Kala jam, Punjabi: Jamalu, Telugu: Neredu chettu, Tamil: Saval naval, Malayalam: Naval, Kannada: Nerale', 
    'Jamun is highly valued in traditional medicine for its numerous health benefits. Every part of the Jamun tree—fruit, seeds, bark, and leaves—has medicinal properties. It is commonly used in Ayurveda for treating diabetes, digestive disorders, and other health issues. The fruit is not only delicious but also nutritious, making it a popular summer treat in many regions.', 
    'The Jamun plant is a medium to large evergreen tree that grows up to 20-30 meters tall. It has dense, glossy green leaves and produces small, round, dark purple to black berries. The berries are sweet and sour in taste and are a rich source of vitamins and minerals. The Jamun tree is widely cultivated in tropical and subtropical regions for its fruit and medicinal properties.', 
    'Native to India, Jamun is also found in tropical and subtropical regions of Southeast Asia, the Pacific Islands, and parts of Africa and South America. It thrives in well-drained, fertile soils and requires a warm climate.', 
    'Fruits: Eugenia triterpenoids A & B, oleanolic acid, malic acid, glucose, fructose, gallic acid, etc. Stem Bark & Root: Kaempferol, myricetin, quercetin. Leaves: Citric, oxalic and glycolic acids; glucose, leucine, sitosterol, dihydromyricetin, etc.', 
    'Rasa: Kaşāya, Madhura, Amla. Guna: Laghu, Rūkşa. Vīrya: Śīta. Vipāka: Katu. Karma: Vātavardhaka, Kapha-pitta hara, Grāhi.', 
    'Fruit, leaf, stem bark', 
    'Fresh juice: 10-20 ml. Powder: 3-6 g.', 
    '1. Diabetes: 10 gm of Jambu seeds powder boiled in 100 ml of water till it is reduced to 1/4th. Take this decoction on an empty stomach early morning to reduce blood sugar levels. 2. Boils: Apply the paste of Jamun seeds powder mixed with a little sesame oil on the boils. 3. Bedwetting: Consume 5gms of Jamun seeds powder with water 2 times a day for 15 days to 1 month in children. 4. Hoarseness of voice: To maintain a good voice and relieve hoarseness, boil the Jamun seeds and gargle with that water frequently. 5. Acne: Mix Jamun seed powder with some cow’s milk and apply it on the pimples at night. Wash in the morning and continue this for a few days for good results. 6. Joint pains: External application of a warm paste prepared from Jamun bark powder mixed with water by rubbing followed by heating is useful to relieve joint pains. 7. Piles: Regular intake of Jamun fruits for 2 to 3 months will help in healing bleeding piles.', 
    '1. Jamun Juice: Blend fresh Jamun fruits with water and a little sugar to make a refreshing juice. 2. Jamun Chutney: Cook Jamun fruits with spices to make a tangy chutney, which can be served with snacks or meals. 3. Jamun Smoothie: Combine Jamun with yogurt, honey, and ice for a nutritious and tasty smoothie.', 
    'Diabetes: While Jamun is beneficial for diabetes, it should be used with caution in people on diabetes medications to avoid hypoglycemia (low blood sugar levels). Pregnancy: Pregnant women should consult a doctor before using Jamun supplements or extracts. Allergy: Some people may be allergic to Jamun. Those with a known allergy should avoid consuming the fruit.', 
    '1. Jamun is propagated through seeds, cuttings, or layering. 2. It thrives in well-drained, fertile soil and requires full sunlight. 3. The tree grows rapidly and is resistant to drought, making it ideal for tropical and subtropical climates.', 
    'Jamun Churna, Jamun Kvath (Decoction), Jamun Fruit Powder'
),
(
    'Mango', 
    'Mangifera indica Linn.', 
    'ANACARDACEAE', 
    'Hindi: Aam, English: Mango, Telugu: Mamidi chettu', 
    'Mango is known as the "King of Fruits" due to its unique flavor and sweetness. It has been an important part of Indian culture and cuisine for centuries, often used in both savory and sweet dishes. In Ayurveda, Mango is used for its medicinal properties, especially in promoting digestion, enhancing immunity, and improving skin health.', 
    'The Mango tree is a large evergreen tree that can grow up to 35-40 meters tall. It has a dense canopy with broad, leathery, glossy leaves. The tree produces large, sweet, and juicy fruits that vary in color from green to yellow, orange, or red when ripe. The fruit has a thick, leathery skin and a central large seed. Mango trees require tropical to subtropical climates and are widely cultivated for their fruits.', 
    'Native to South Asia, the Mango is now cultivated in tropical and subtropical regions around the world, including India, Southeast Asia, Africa, the Americas, and Australia. It is one of the most popular and widely cultivated tropical fruits globally.', 
    'Mangiferin, mangiferolic acid, homonangiferin, indicenol.', 
    'Rasa: Kaṣāya (Bark, Seed), Vīrya: Śīta, Guna: Laghu, Vipāka: Katu, Karma: Vātahara (ripe fruit), Kapha-pittahara (other parts), Hrdya, Grāhi.', 
    'Stem bark, leaf, flower, seed kernel', 
    'Fresh juice: 10-20 ml. Decoction: 50-100 ml. Powder: 3-6 g.', 
    '1. Digestive Health: Mango helps improve digestion by stimulating appetite and aiding in the breakdown of food. It is commonly used to treat indigestion, acidity, and constipation. 2. Skin Health: Mango is beneficial for the skin due to its high vitamin C and antioxidant content. It helps reduce wrinkles, delays signs of aging, and improves skin tone. Mango pulp or oil is used in various face masks and skincare formulations. 3. Boosts Immunity: The high content of vitamin C in Mango strengthens the immune system and helps the body fight infections and illnesses. 4. Heart Health: Mango helps lower cholesterol levels and is considered heart-healthy due to its rich content of antioxidants and fiber. 5. Eye Health: Mango is rich in beta-carotene and vitamin A, which are essential for good eyesight and can help prevent age-related macular degeneration and cataracts. 6. Liver Health: Mango has detoxifying properties and can support liver health by improving liver function and aiding in detoxification. 7. Weight Loss: Mango, when consumed in moderation, can help with weight management by promoting fat metabolism and improving digestive health. 8. Anti-inflammatory: Mango has anti-inflammatory properties that help reduce inflammation in the body, which can be beneficial in conditions like arthritis. 9. Blood Pressure Regulation: The potassium content in Mango helps maintain healthy blood pressure levels and reduce the risk of hypertension.', 
    '1. Mango Lassi: Blend ripe Mango pulp with yogurt, water, and sugar to make a refreshing Mango lassi. 2. Mango Chutney: Cook Mango with spices such as ginger, mustard seeds, and chili to make a tangy chutney, perfect with Indian dishes. 3. Mango Sorbet: Puree Mango and freeze it with a little sugar to create a refreshing summer sorbet. 4. Mango Smoothie: Blend Mango with milk or yogurt and a dash of honey for a creamy smoothie.', 
    'Sugar Content: Mangoes are naturally high in sugar. Diabetic patients should consume them in moderation. Allergy: Some individuals may have an allergic reaction to Mango, especially to its skin or sap. People allergic to poison ivy may also be allergic to Mango. Pregnancy: While Mango is generally safe during pregnancy, consuming it in moderation is recommended. Excessive consumption may lead to acidity or digestive issues.', 
    '1. Mango is propagated by seeds, grafting, or budding. 2. Grafting is the preferred method as it ensures the fruit quality is preserved. 3. Mango trees require well-drained, fertile soil and a warm tropical or subtropical climate to thrive. 4. They grow best in full sunlight.', 
    'Mango Seed Powder, Mango Leaf Decoction, Mango Pulp Face Mask'
),
(
    'Neem', 
    'Azadirachta indica A. Juss (Melia azadirachta Linn.)', 
    'MELIACEAE', 
    'Hindi: Nim, English: Margosa tree or Neem tree, Telugu: Vepa chettu, Malayalam: Veppu, Tamil: Vembu, Gujarati: Limado', 
    'Neem is revered in Ayurveda for its versatile medicinal properties. It has been used for centuries in traditional medicine as a natural remedy for various ailments. It is often referred to as the "village pharmacy" because every part of the Neem tree—leaves, bark, seeds, and flowers—has medicinal applications. Its bitter and antimicrobial properties make it highly effective for skin care, oral health, and general detoxification.', 
    'It is a large tree growing up to 18 m high with almost a straight trunk. Leaves: pinnate, crowded at the ends of branches. Leaflets: 5-15, opposite, subopposite or alternate; lanceolate, acuminate, serrate or dentate, glabrous. Flowers: numerous, white, honey-scented. Fruits: 1-seeded drupes, oblong, yellow when ripe. Seeds: contain oil.', 
    'Native to the Indian subcontinent, Neem is also found in tropical and subtropical regions of Asia, Africa, and Central and South America. It thrives in a variety of soils, particularly in dry, sandy, and rocky regions.', 
    'Leaves: Azadirachtin, azadirachtol, azadirachnol, melianone, nimbiol, nimocin, etc. Bark: Nimbin, nimbidin, nimbinin, sitosterol, kulinone, margosinolide, etc. Seeds: Azadirachtin, azadirone, nimbidiol, nimbin, nimbolide, etc. Seed Oil: (40-49% oil) - Tocopherol, azadirone, azadiradione, nimbinin, salannol, nimbin, etc. Flowers: Azadiradione, margosene, linoleic acid, arachidic acid, etc.', 
    'Rasa: Tikta, Kasaya, Vīrya: Sita, Guna: Laghu, Rūkşa, Vipāka: Katu.', 
    'Root bark, Stem bark, gum, flower, leaves, seeds, seed oil', 
    'Bark powder: 2-4 g, Fresh juice: 10-20 ml, Seed oil: 5-10 drops.', 
    '1. Dental plaque/gingivitis: Gargling with warm decoction of Neem leaves twice daily and brushing with twigs of Neem. 2. Skin diseases: Intake of powder of Neem leaves and application of Neem oil. 3. Upset stomach: Decoction of Neem leaves helps in abdominal pain and worm infestation. 4. Insect repellent: Applying Neem oil to the skin to protect against mosquitoes. 5. Other uses: Neem is an antifungal, anti-parasitic, antioxidant, anti-inflammatory, neuroprotective, and liver-protective agent used for conditions like jaundice.', 
    '1. Neem flower chutney along with raw mango and green chili, or tender leaves fried in oil with red chili, asafoetida, and ajwain seeds, ground with tamarind, salt, and jaggery for a savory chutney. 2. Neem Juice: A healthy detox drink made from fresh Neem leaves, water, and honey. 3. Neem Powder Smoothie: Mix Neem powder with yogurt, honey, and fruits for a detoxifying smoothie.', 
    'Neem may cause nausea and vomiting due to its bitterness. Excessive doses can affect sperm count, so it may not be suitable for men planning for family. Neem should be used cautiously during pregnancy, lactation, and in children.', 
    '1. Neem trees are often self-sown in gardens, with seedlings quickly colonizing under mature trees. It can thrive in poor, dry soils and survive damage by using root suckers. 2. Propagation is mainly by seed but can also be achieved using root shoots and root cuttings.', 
    'Mahanarayan Oil, Nimba Churna, Neem Oil, Tiktaka Ghrita.'
),
(
    'Onion', 
    'Allium cepa Linn.', 
    'LILIACEAE', 
    'Hindi: Pyaz, English: Onion, Telugu: Ullipāya', 
    'Onion, commonly used as a culinary vegetable, has been an integral part of traditional medicine for centuries. Known for its distinctive aroma and flavor, onion is used in both raw and cooked forms in various cuisines. In Ayurveda, it is regarded for its numerous health benefits, including its ability to improve digestion, boost immunity, and reduce inflammation.', 
    'Onion is a bulbous plant that belongs to the Allium genus. It has a round shape with a papery outer skin that is usually yellow, white, or red. The plant produces long green leaves and small, white or purple flowers. The bulb of the onion is composed of fleshy layers, which are used in cooking for their pungent flavor. Onions are typically grown in well-drained, fertile soil and require a temperate or tropical climate to thrive.', 
    'Onions are widely cultivated throughout the world, particularly in regions with temperate climates. They are grown in Asia, Europe, North America, and parts of Africa. India is one of the largest producers of onions globally.', 
    'Cycloallin, quercetin, oleanolic acid etc.', 
    'Rasa: Madhura, Katu, Vipāka: Amla, Vīrya: Anuşna, Guna: Guru, Snigdha, Tīkşna, Karma: Vātahara, Vṛṣya, Rasāyana.', 
    'Bulb, seeds', 
    'Juice 10-20 ml, seed powder 1-3 g.', 
    '1. Bleeding piles: 20ml of raw white onion juice should be taken on an empty stomach daily in the morning. 2. High Cholesterol: Take half a cup of raw onion juice mixed with one teaspoonful of honey and ginger juice; this reduces the bad cholesterol levels in the blood. 3. Vision: Internal administration of the juice of onion in a dose of 10-15ml daily is beneficial to improve the vision. 4. Cough: The slices of onion are fried in ghee and taken internally to treat cough. 5. Nasal bleeding: White onion juice 2-3 drops is installed into nostrils. 6. Dental caries: The paste of onion is kept over the area affected with dental caries and inflammation of the gum.', 
    '1. Onion Soup: A warming soup made with sautéed onions, garlic, and broth. It can be seasoned with herbs for added flavor. 2. Onion Chutney: A tangy chutney made with onions, tamarind, and spices, often served with Indian breads or rice. 3. Caramelized Onions: Slow-cooked onions in butter or oil until golden and sweet, often used as a topping for burgers, steaks, or salads. 4. Onion Bhaji: A crispy Indian snack made by deep-frying a batter of onions, chickpea flour, and spices.', 
    'Excessive Consumption: Consuming large amounts of raw onion can cause digestive irritation, especially for people with sensitive stomachs. Allergy: Some individuals may be allergic to onions, experiencing symptoms such as rashes, swelling, or difficulty breathing. Blood Thinning: Onions have natural blood-thinning properties, so they should be consumed with caution by people on anticoagulant medications. Pregnancy: While onions are generally safe during pregnancy, excessive consumption should be avoided, especially in raw form.', 
    '1. Onions are typically propagated by seeds, bulbs, or sets. 2. Seeds are the most common method of propagation, and onions are planted in well-drained, fertile soil. 3. They require a moderate climate and full sunlight to thrive.', 
    'Onion Juice, Onion Paste, Onion Oil, Onion Soup.'
),
(
    'Papaya', 
    'Carica papaya Linn.', 
    'Caricaceae', 
    'English: Papaya, Papaw. Hindi: Papaya, Kannada: Papaya, Malayalam: Papaya, Karmmus, Sanskrit: Erand-karkati, Tamil: Pappaali, Pappayi, Telugu: Bappayi', 
    'Papaya is a widely consumed fruit, known for its sweet taste and health benefits. It is rich in vitamins and minerals, and its enzymes, such as papain, are known for their digestive properties. In traditional medicine, papaya has been used to treat a variety of ailments, including digestive disorders, inflammation, and skin conditions. Both the fruit and the leaves of the plant are used for medicinal purposes.', 
    'A tree 7 to 8 m high. Branches – absent. Stalk: straight and rough. Leaves: resemble the leaves of castor and have 7 angles. Stalk of leaf is 1 m in length and hollow. Flowers: homosexual. Fruits: oval, when raw are green and yellow when ripe. Raw fruit oozes latex on cutting. Seeds: numerous and blackish grey.', 
    'Not basically Indian but mainly from South America and Brazil. The Portuguese brought it to India. Papeeta is its Portuguese name; however, it now grows all over India.', 
    'Papain, chymopapain, alkaloids carpaine, pseudocarpaine.', 
    'Guna: Laghu, Ruksha, Tikshna. Rasa: Katu, Tikta. Vipaka: Katu. Veerya: Ushna. Karma: Vranahara, Krimighna, Jwaraghna, Deepana, Pachana, Keshya, Stomachic, Digestive, Carminative, Diuretic, Galactagogue. Used for bleeding piles, haemoptysis, dysentery, chronic diarrhea, emmenagogue, and vermifuge.', 
    'Resin, Leaves, Fruit, Seed', 
    'Leaf juice: 10-15 ml. Hot infusion: 4 to 5 gms. Latex: 6 to 12 ml. Digestive principle: 1 to 8 gunja (125-625 mgs). Powdered seeds: 4 to 8 gunja.', 
    '1. Worm infestation: Administration of 30ml of raw fruit juice of Erandakarkati (papaya) with honey once a day for 1 week is beneficial to expel intestinal worms. Regular intake of boiled fruit expels the worms, especially Pinworm. 2. Menstrual irregularities: Regular intake of raw papaya also acts as a uterine tonic and cures ailments pertaining to reproductive organs. However, consumption of the fruit should be avoided during pregnancy as sometimes it may lead to abortion. 3. Face pigmentation: The paste prepared from ripened papaya fruit pulp with fresh milk is an excellent face pack. It moisturizes the skin and removes hyperpigmentation. 4. Dengue fever: Papaya leaf juice administered in doses of 10 to 20 ml, 3 to 4 times a day, helps in restoring platelet count and decreases fever. 5. Eye disease: Papaya fruit rich in Vitamin A and Carotene prevents eye disease and promotes vision. 6. Dysentery: 3gms of papaya seed powder with warm water twice daily before food is beneficial due to antibacterial properties.', 
    '1. Papaya Smoothie: Blend papaya with yogurt, milk, and honey for a refreshing and healthy drink. 2. Papaya Salad: Mix fresh papaya with lime juice, chili, and salt for a tangy and spicy salad. 3. Papaya Curry: A savory dish made with green papaya, spices, and coconut milk, typically served with rice. 4. Papaya Juice: Fresh papaya juice with lime and mint can be a nutritious beverage.', 
    'Pregnancy: Pregnant women should avoid consuming raw papaya, especially the unripe fruit, as it contains latex that can trigger uterine contractions. However, ripe papaya is safe in moderation. Allergy: Some individuals may be allergic to papaya or its enzymes, causing symptoms like itching, swelling, or rash. Excessive Consumption: Overconsumption of papaya, especially unripe fruit, can lead to digestive discomfort or diarrhea due to laxative effects.', 
    '1. Papaya is propagated by seeds, which are collected from ripe fruits and sown in fertile, well-drained soil. 2. The plant grows best in tropical climates and requires full sunlight. 3. The plant can also be propagated through stem cuttings in some cases.', 
    'Papaya Juice, Papaya Leaf Extract, Papaya Seed Powder, Papaya Face Pack.'
),
(
    'Panfuti', 
    'Bryophyllum calycinum Salish. (Kalanchoe pinnata Pers.)', 
    'CRASSULACEAE', 
    'Hindi: Jhakmehayat, Telugu: Ranapalaku, Bengali: Koppata, Goipta, Gujarati: Chamari', 
    'Panfuti, or Phyllanthus niruri, is known for its medicinal properties, particularly its ability to treat kidney stones, urinary tract infections, and liver disorders. It is called "Stonebreaker" in English due to its long-standing use in traditional medicine as a remedy for stones in the kidney and gallbladder. It is considered an important plant in Ayurvedic and folk medicine and has gained significant attention in recent years for its potential health benefits.', 
    'Panfuti is a small, herbaceous plant that typically grows up to 30-60 cm in height. It has narrow, lance-shaped leaves and small yellow-green flowers. The plant produces small, smooth, globular fruits that contain seeds. It has a dense, branching habit and is commonly found in tropical and subtropical regions, thriving in sandy or loamy soils. The plant has a slightly bitter taste and is commonly used in herbal remedies, especially for its ability to treat kidney stones.', 
    'Panfuti is widely distributed in tropical and subtropical regions, especially in India, Southeast Asia, Africa, and the Caribbean. It grows in fields, along roadsides, and in disturbed soil areas.', 
    'n-alkanes, n-primary alcohols, fumaric acid, bryophyllin etc.', 
    'Rasa: Kaṣāya, Amla; Vīrya: Śīta; Guna: Laghu, Rūkṣa; Vipāka: Madhura; Karma: Kapha-pitta hara, Raktastambhana, Vranaropana', 
    'Leaf', 
    'Fresh juice 10-20 ml.', 
    '1. Urinary calculi: 10 gms of Panfuti leaves in 100 ml of water, taken twice a day. You can also give the decoction with 500 mg Shilajit and 2 tsp of honey mixed in it for more effective results. 2. Boils: Slightly warm Panfuti leaves and crush them. Tie it as a poultice and apply on the affected area to cure boils, redness, and swelling. 3. Wounds: Slightly warm Panfuti leaves and then crush them and tie on the wound. It helps the wound heal faster and also eliminates the scar. 4. Bleeding diarrhea: Administer 3-6 gms juice of Panfuti leaves with cumin seeds and double the quantity of ghee, thrice a day to control blood flow in diarrhea. 5. Cold: Administer 5 ml juice of Panfuti three times a day. 6. Joint pains: Grind 7 fresh leaves into a poultice. Apply the poultice evenly to the affected area twice a day, morning and night, as often as needed to get relief from joint pains.', 
    '1. Panfuti Decoction: Boil Panfuti leaves in water and strain to drink as a daily remedy for kidney stones and urinary health. 2. Panfuti and Honey Syrup: Mix Panfuti juice with honey and consume to treat fever and cold. 3. Panfuti Tea: Make tea by steeping dried Panfuti leaves in hot water. It helps in digestion and detoxification.', 
    '1. Pregnancy: Pregnant women should avoid using Panfuti, as it may cause uterine contractions. 2. Kidney Issues: Although Panfuti is used for kidney stones, excessive use can affect kidney function. It is important to use it under the guidance of a healthcare professional. 3. Allergies: People with a known allergy to plants in the Euphorbiaceae family should avoid using Panfuti. 4. Dosage: Overuse may cause digestive irritation. Stick to recommended doses to avoid side effects.', 
    '1. Panfuti is propagated by seeds, which are collected from the mature plant and sown in well-drained soil. 2. The plant thrives in tropical and subtropical climates and prefers areas with adequate sunlight. 3. It grows well in sandy loam soil with good water drainage.', 
    'Panfuti Churna, Panfuti Decoction, Panfuti Oil, Panfuti Syrup'
),
(
    'Satyanashi', 
    'Argemone mexicana', 
    'PAPAVERACEAE', 
    'Hindi: Satyanashi, English: Prickly Poppy, Telugu: Pedda Jilledu, Tamil: Sillitoragai', 
    'Satyanashi is a herbaceous plant known for its medicinal properties and its ability to cause hallucinations. It is often found in wastelands and along roadsides. While it has been used in traditional medicine, it is important to note that it can be toxic if not used correctly.', 
    'Habit: Annual, prickly herb. Height: 30-100 cm. Stem: Erect, branched, and spiny. Leaves: Alternate, spiny, lobed, and toothed. Flowers: Solitary, showy, yellow or white. Fruit: Prickly capsule containing numerous seeds.', 
    'Native to tropical Asia and widely distributed in India, Myanmar, Thailand, and parts of Southeast Asia. It is commonly found in dry, tropical regions.', 
    'Alkaloids: Argemone alkaloids like sanguinarine, berberine, and protopine. Fatty acids. Sterols.', 
    'Rasa: Tikta, Katu. Vipāka: Katu. Vīrya: Uṣṇa. Guna: Laghu, Ruksha, Tīkṣṇa. Karma: Kapha-Vātahara, Krimighna, Lekhana.', 
    'Leaves, Seeds, Roots', 
    'Seeds: 250-500 mg, twice daily (under medical supervision). Paste of leaves or seeds applied topically.', 
    '1. Eczema: The yellow latex, possessing antibacterial properties, is applied along with turmeric to treat skin infections like eczema, itching, boils, and skin ulcers. 2. Wounds: A paste or poultice of the leaves is applied to heal wounds. 3. Mosquito repellent: The leaf and seed extract possesses larvicidal properties to repel mosquitoes. 4. Ringworm: A decoction of fresh leaf paste (20 gms boiled in 200 ml water, reduced to 50 ml) is used to wash affected areas. 5. Headache: A decoction of 5 gms of plant root boiled in 100 ml water (reduced to 25 ml) is taken with jaggery for migraines. 6. Joint pains: Sesame oil processed with Mexican poppy seeds is applied externally for relief.', 
    '1. Seeds are sometimes used as a substitute for poppy seeds. 2. Satyanashi Leaf Decoction: Boil fresh leaves in water for 10-15 minutes, strain, and drink as a remedy for fever and digestive issues. 3. Satyanashi Bark Powder: Mix powdered bark with honey or warm water for pain relief and digestive health.', 
    'Toxicity: The plant is toxic and can cause serious side effects if ingested in large quantities. Skin Irritation: The spiny leaves and stems can cause irritation. Hallucinogenic Effects: The alkaloids in the plant can cause hallucinations and other adverse effects.', 
    'Satyanashi propagates primarily through seeds. The seeds are dispersed by wind and animals.', 
    'Vrana Ropana Aushadhis, Rakta Pittahara Aushadhis.'
),
(
    'Shatavari', 
    'Asparagus racemosus', 
    'LILIACEAE', 
    'Hindi: Satavare, English: Shatavari, Telugu: Pillipichara, Kannada: Majjige gadde, Tamil: Sadavare, Marathi & Gujarati: Śatavar', 
    'Shatavari, often referred to as the \"queen of herbs,\" is highly regarded in Ayurveda for its numerous health benefits, particularly for women\'s health. It is known for its rejuvenating, restorative, and adaptogenic properties. The root of Shatavari is rich in saponins, alkaloids, and other bioactive compounds, which contribute to its therapeutic effects. It has been used for centuries to balance the body\'s energy and support a healthy reproductive system.', 
    'A tall climbing undershrub with annual woody terete stems. Spines 5-13 mm long, recurved. Cladodes 1.3-2.5 cm long, in tufts of 2-6, curved. Flowers: white, fragrant, in solitary or fascicled, simple or branched racemes 2.5-5 cm long. Fruit: berry, 5-6 mm diameter, red.', 
    'Shatavari is native to the Indian subcontinent and is commonly found in parts of India, Nepal, Sri Lanka, and some regions of Southeast Asia. It grows well in tropical and subtropical climates and is often cultivated in gardens and herbal farms.', 
    'Roots: Sarsapogenin, two spirostanolic & two furostanolic saponins, Sitosterol, Asparagamine A. Fruits: Sitosterol, sarsasapogenin, diosenin, asparamins A & B. Leaves: flavonoids, rutin.', 
    'Rasa: Madhura, Tikta. Guna: Guru, Snigdha. Virya: Sita. Vipāka: Madhura. Karma: Vāta-pittahara, Rasāyana, Vṛṣya, Stanyajanana.', 
    'Tuberous roots.', 
    'Fresh juice 10-20 ml; decoction 50-100 ml; powder 3-6 g.', 
    '1. To increase breast milk: 3-5 gm of root powder or 2 spoons of Shatavari root juice taken with 1 glass of milk twice daily enhances milk in lactating mothers. 2. As a tonic: Shatavari root powder 1 to 3 gm is taken with milk twice daily to overcome fatigue. It is useful in age-related problems such as bone and neuro degeneration. 3. Hyper acidity and peptic ulcer: Intake of 2-4 spoon of juice of Shatavari root or 1 to 3 gm of powder daily will be helpful to reduce hyperacidity and peptic ulcers. 4. Reproductive health: 1 to 3 grams of Shatavari powder one to two times a day is useful to prevent menopausal symptoms and osteoporosis. The powder is recommended in non-specific infertility.', 
    '1. Shatavari Latte: Heat a cup of milk (dairy or plant-based) in a saucepan. Add 1 teaspoon of Shatavari powder, a pinch of turmeric powder, and a pinch of cardamom powder. Heat for a few minutes, stirring occasionally. Sweeten with honey or jaggery to taste. 2. Shatavari Smoothie: Blend together 1 banana, a handful of berries, a cup of spinach, 1 teaspoon of Shatavari powder, and a cup of your favorite milk. 3. Shatavari Energy Balls: Mix 1 cup of pitted dates, 1/2 cup of almond butter, 1/2 cup of rolled oats, 1/4 cup of Shatavari powder, and 1/4 cup of chopped nuts in a food processor. Roll into balls and refrigerate. 4. Shatavari Tea: Steep 1 teaspoon of Shatavari powder in a cup of hot water for 5-10 minutes. Strain and sweeten with honey or lemon to taste.', 
    'Shatavari is safe to be used within the recommended quantity in a normal person. Sensitivity may cause allergic reactions in some people such as skin rashes or breathing difficulty on intake of large doses. In case of any medical problems or other medications, please follow the advice of a qualified doctor.', 
    '1. The seeds are used for propagation in nurseries; however, the vegetative method is more suitable for growing in households. 2. The vegetative propagation is by division of the rhizomatous disc present at the base of the aerial stem. 3. The rhizomatous disc develops several vegetative buds around the aerial shoots. 4. The disc is divided in such a way that each piece possesses at least two buds along with 2-3 tuberous roots. 5. These pieces are planted, covering the buds with 1 cm of soil followed by watering. The sprouting commences in 8-10 days after plantation.', 
    'Shatavari Ghrita, Shatavari Kalpa, Shatavari Churna.'
),
(
    'Sugarcane', 
    'Saccharum officinarum', 
    'POACEAE', 
    'Hindi: Ganna, Telugu: Chinna, Bengali: Aakh, Tamil: Kambi, Marathi: Ushas', 
    'Sugarcane, a tall perennial grass, is one of the world\'s most important crops, primarily cultivated for sugar production. Its sweet juice, extracted from the stalks, has been used for centuries for both culinary and medicinal purposes. Beyond its culinary uses, sugarcane and its byproducts have a significant role in various industries, including biofuels and pharmaceutical.', 
    'Habit: Tall, perennial grass. Height: 2-6 meters. Stem: Jointed, fibrous stalks rich in sucrose. Leaves: Long, linear, green with serrated edges. Inflorescence: Panicle, pinkish plume. Fruit: Dry, single-seeded.', 
    'Sugarcane is primarily cultivated in tropical and subtropical regions worldwide, including India, China, Brazil, and Thailand. It thrives in warm, sunny climates with well-irrigated fields and requires plenty of water and rich soil for optimal growth.', 
    'Sugars: Sucrose, glucose, fructose. Fiber: Cellulose, hemicellulose, lignin. Minerals: Potassium, calcium, magnesium, iron, phosphorus. Vitamins: Vitamin C, B-complex vitamins. Organic acids: Citric, malic, oxalic acids. Phenolic compounds: Flavonoids (orientin, tricin, luteolin), phenolic acids (ferulic, p-coumaric).', 
    'Rasa: Madhura. Vīrya: Ushna. Guna: Snigdha, Guru. Vipāka: Madhura. Karma: Balya, Vrishya, Tridoshahara.', 
    'Stem', 
    'Fresh juice: 50-100 ml, twice daily', 
    '1. Rich in Nutrients: Sugarcane juice is a good source of vitamins and minerals, providing energy and hydration. 2. Digestive Aid: It helps in digestion and relieves constipation. 3. Skin Health: The juice can soothe skin irritations and promote healthy skin. 4. Aphrodisiac: Considered to have aphrodisiac properties. 5. Respiratory Health: Can help relieve cough and cold symptoms.', 
    '1. Sugarcane Juice: A refreshing and hydrating beverage, often enjoyed with lime and mint. 2. Sugarcane Syrup: Used in desserts, cocktails, and as a sweetener. 3. Jaggery: A traditional Indian sweetener made by boiling sugarcane juice and evaporating the water. 4. Sugarcane Sweets: Candies and other confections made with sugarcane.', 
    'Excessive Consumption: While sugarcane is beneficial, excessive consumption can lead to weight gain and dental issues. Diabetes: People with diabetes should consume sugarcane in moderation and consult with a healthcare professional. Allergies: Some individuals may be allergic to sugarcane or its byproducts.', 
    '1. Sugarcane is primarily propagated through stem cuttings. 2. A mature sugarcane stem is cut into pieces, each with at least two nodes. 3. These cuttings are then planted in the soil, where they root and develop into new plants.', 
    'Chandraprabha Vati, Dashmula Kadha, Chyawanprash, Sakharrasa.'
),
(
    'Tandulja', 
    'Amaranthus viridis', 
    'AMARANTHACEAE', 
    'Hindi: Chhoti Chaulai, Telugu: Thotakura, Bengali: Notey Shaak, Gujarati: Tandaljo', 
    'Tandulja is widely recognized in traditional medicine systems and Ayurveda for its nutritive and medicinal properties. It is used as a leafy vegetable in many parts of India and has references in Ayurvedic texts for its utility in managing pitta and vata-related conditions.', 
    'Tandulja is an annual herbaceous plant that grows up to 1 meter in height. Its leaves are ovate, and the plant produces small, greenish flowers in dense clusters.', 
    'Throughout India, particularly in fields, gardens, and roadside areas.', 
    'Amaranthine, Betacyanins, Phenolic compounds, Saponins', 
    'Rasa: Tikta, Madhura. Vīrya: Śīta. Guna: Laghu, Snigdha. Vipāka: Madhura. Karma: Pitta-pacifying, Vata-pacifying, Raktaprasadana (blood purifier).', 
    'Leaves', 
    'Fresh leaf juice: 10-20 ml. Leaf paste for external application as required.', 
    '1. Blood Purification: The plant\'s juice is effective in detoxifying blood and managing disorders like Raktapitta (bleeding disorders). 2. Wound Healing: Leaf paste or juice promotes faster healing of wounds and reduces inflammation. 3. Digestive Health: Tandulja leaves alleviate indigestion and act as a gentle laxative. 4. Anemia: The iron-rich leaves are beneficial for improving hemoglobin levels and managing anemia. 5. Urinary Disorders: Acts as a diuretic, helping in detoxifying the urinary system and managing conditions like dysuria. 6. Skin Disorders: The paste of leaves is used externally to treat skin rashes and irritation. 7. Heat Regulation: Helps in cooling the body and is effective in managing pitta-related disorders like acidity and excessive body heat.', 
    '1. Tandulja Saag: The tender leaves are sautéed with garlic, cumin, and mustard seeds. Often consumed with rice or roti. 2. Dal Tandulja: Cooked lentils are mixed with boiled Tandulja leaves for a nourishing dish. 3. Leaf Soup: A light, flavorful soup prepared with Tandulja leaves, ginger, and black pepper.', 
    'Avoid excessive consumption, as it may lead to mild gastrointestinal discomfort. Pregnant and lactating women should consult a healthcare provider before use.', 
    '1. Tandulja is propagated through seeds. 2. It grows easily in well-drained soil under warm and sunny conditions.', 
    'Tandulja Swarasa, Tandulja Lepa'
),
(
    'TouchMeNot', 
    'Mimosa pudica Linn.', 
    'MIMOSACEAE', 
    'Hindi: Lagalu, Telugu: Attipatti', 
    'Touch Me Not is well-known for its unique response to touch. It has been used for centuries in traditional medicine for a variety of ailments, particularly in Ayurveda and other indigenous healing practices. The plant is known for its ability to move its leaves in response to touch, a phenomenon called "thigmonasty," which is believed to be a defense mechanism. In addition to its fascinating behavior, it has therapeutic applications due to its rich phytochemical profile.', 
    'The Touch Me Not plant is a small, creeping herb with compound leaves. Its most notable feature is its sensitivity to touch; the leaves fold inward when disturbed. The plant can grow to about 30–50 cm in height. The stems are slender and covered with small, soft, yellowish-green thorns. It produces small, pink or purple spherical flowers, and its fruits are pods containing several small seeds.', 
    'Mimosa pudica is found throughout tropical and subtropical regions of the world. It grows as a weed in gardens, fields, and roadsides. It thrives in well-drained, moist soil under full sunlight.', 
    'Mimosine, orientin, isoorientin, etc.', 
    'Rasa: Kaşaya, Tikta. Virya: Šita. Vipäka: Kațu. Guna: Laghu, Rükşa. Karma: Kapha-pitta hara, Sandhānīya, Purşasangrahaniya.', 
    'Root, whole plant', 
    'Fresh juice: 10-20 ml.', 
    '1. Diabetes: Intake of 15-20ml of whole plant juice of Lajjalu in early morning on an empty stomach is beneficial in diabetes. 2. Leucorrhea: The whole plant of Lajjalu powder given in the dose of 5 grams with rice water twice daily cures leucorrhea. 3. Fungal infection: One part of the juice of Lajjalu plant is boiled with 4 parts of tila oil. This oil is externally applied over the affected area and is useful to treat fungal infections. 4. Wound: 20gms of the whole plant of Lajjalu paste boiled in 200 ml of water till it is reduced to 50ml decoction. This is used to wash ulcers, diabetic ulcers, skin infections, etc., as it has significant wound healing activity. 5. Piles: Lajjalu leaves fine paste should be applied as a poultice regularly on piles. It greatly eases the burning and bleeding.', 
    '1. Touch Me Not Leaf Tea: Boil fresh Mimosa pudica leaves in water to make a soothing tea that helps with digestive health and reduces anxiety. 2. Mimosa Pudica Powder: Dry the leaves and grind them into powder. Mix with honey or water and consume for general health benefits.', 
    'Pregnancy: Pregnant women should consult a healthcare professional before using Mimosa pudica, as it may have uterine-stimulating effects. Allergy: Some individuals may be allergic to the plant, particularly when it is applied topically. A patch test is recommended before applying it to large areas of the skin. Excessive Consumption: High doses of Mimosa pudica might cause nausea, vomiting, or other digestive discomforts. Diabetes: While beneficial for diabetics, it is important to monitor blood sugar levels when consuming the plant regularly.', 
    '1. Mimosa pudica is propagated by seeds or by cutting the plant into sections and replanting them. 2. The seeds are small and should be planted in well-drained soil, with moderate watering and exposure to sunlight. 3. The plant grows well in tropical and subtropical climates and can be cultivated in gardens or fields.', 
    'Lajavanti Churna (Powder), Mimosa Pudica Decoction, Mimosa Pudica Oil'
);


select * from plant_info;

use user_database;
select * from users;

use plants;
select * from plant_info;
desc plant_info;
desc users;
create table history(username varchar(50), plant_name varchar(225), time timestamp);
desc history;
select * from history;